### PR TITLE
Automatically remove expired join request quizzes 

### LINKED ISSUE #11: remove join request quizes after a fixed period of time

### PR DESCRIPTION
**Pull request by shahriaarrr**
fixed #11 :
- Added a `cleanup_old_quizzes` method to delete expired quizzes from the KV store.
- Introduced `start_cleanup_task` to run periodic cleanup tasks in the background.
- Configured quiz expiration to be managed independently and seamlessly.

### CODE REVIEW

**Comment by shahriaarrr** [comment]
@amiremohamadi

**Comment by shahriaarrr** [comment]
now i should think about it :**)

**Comment by amiremohamadi** [comment]
cf workers resources are limited so we can't rely on common approaches like spawning threads and sleeping.

**Comment by amiremohamadi** [comment]
these are the potential approaches we can try:
- check if there's a way to pass callbacks to kv expired entries
- using cf queues and `deliveryDelay` (not sure, probably only available on paid plans)
- using cf cron triggers

**Comment by amiremohamadi** [comment]
i'm closing this as it's fixed in #23

**Pull request closed without merging**
